version: "3.9"

services:
  apollo:
    image: apollo
    build:
      context: ./apollo
    ports:
      - 31121:3000

  jupyter:
    image: jupyter/tensorflow-notebook
    restart: always
    ports:
      - 31002:8888
    volumes:
      - .:/home/jovyan/work

  gql_ug:
    image: gql_ug
    build:
      context: ./gql_ug
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    depends_on:
      - postgres
    ports:
      - 31120:8000

  gql_events:
    image: gql_events
    build:
      context: ./gql_events
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    depends_on:
      - postgres

  gql_project3:
    image: gql_project3
    build:
      context: ./gql_project3
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    depends_on:
      - postgres
      - gql_ug
    ports:
      - 31128:8000  

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=anoyne@anywhere.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - 31122:80

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80  #50081:80
    depends_on:
      - postgres
      - apollo